version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      SECRET_NAME: ${SECRET_NAME}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - .:/app
    command: uvicorn project.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      SECRET_NAME: ${SECRET_NAME}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      MONGODB_URI: ${MONGODB_URI}
    command: celery -A project.celery_worker worker --loglevel=info

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
